apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webservices-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: my-webservices-group8.com
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port: 
                  number: 7777
          - path: /users/login
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port: 
                  number: 7777
          - path: /users/validation
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port: 
                  number: 7777
          - path: /
            pathType: Prefix
            backend:
              service:
                name: url-service
                port: 
                  number: 5000
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
  - 172.16.14.80-172.16.14.90
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
  - default