apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-deployment
  labels:
    app: url
spec:
  replicas: 1   # set the number of desierd pods as 3
  selector:  # used to connect with pod
    matchLabels:
      app: url
  template:  # define the pod
    metadata:
      labels:
        app: url
    spec:
      containers:
      - name: url
        image: clytze/url-service:v6
        ports:
        - containerPort: 5000
        env:
          - name: USER_NAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: USER_PWD
            valueFrom:
              secretKeyRef: 
                name: mongo-secret
                key: mongo-pwd
          - name: DB_URL
            valueFrom:
              configMapKeyRef: 
                name: mongo-config
                key: mongo-url
       # - name: database
          #valueFrom:
           # configMapKeyRef:
           #   name: mongo-configmap
            #  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: url-service
spec:
  selector:
    app: url
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000   # targetport is lisening to the conatinerport
  type: LoadBalancer