version: '1.0'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    expose:
      - "27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ~/mongo/data:/data/db

  auth-service:
    build: ../web-authentication
    # image: reisafriche/auth-service:v1
    container_name: auth-service
    expose:
      - "7777"

  url-service:
    build: ../web-URL-shortener
    # image: reisafriche/url-service:v5
    container_name: url-service
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - url-service
    restart: always
